/*
 *
 * Homepage constants
 *
 */

export const DEFAULT_ACTION = 'app/Homepage/DEFAULT_ACTION';

export const ACTION_GET_IMAGES = {
  IMAGES: 'IMAGES',
  GET_IMAGES: 'GET_IMAGES',
  GET_IMAGES_SUCCESS: 'GET_IMAGES_SUCCESS',
  GET_IMAGES_ERROR: 'GET_IMAGES_ERROR',
  SAVE_IMAGES: 'SAVE_IMAGES',
};
